#!/bin/sh
# DirtSim configuration setup - runs once at boot before services start.
# Ensures proper permissions for config files and directories.

# Fix permissions on .local config overrides so dirtsim user can read them.
if ls /etc/dirtsim/*.local >/dev/null 2>&1; then
    chmod 644 /etc/dirtsim/*.local
    echo "Fixed permissions on /etc/dirtsim/*.local"
fi

# Pick default ALSA card with USB audio preferred, HDMI as fallback.
# Wait briefly for USB audio to enumerate on boot.
if [ ! -r /proc/asound/cards ]; then
    for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
        [ -r /proc/asound/cards ] && break
        sleep 0.2
    done
fi

if [ -r /proc/asound/cards ]; then
    audioCard=""
    for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
        audioCard=$(awk '/Picade USB Audio/{print $1; exit}' /proc/asound/cards)
        [ -n "$audioCard" ] && break
        sleep 0.2
    done
    if [ -z "$audioCard" ]; then
        audioCard=$(awk '/vc4hdmi/{print $1; exit}' /proc/asound/cards)
    fi
    if [ -n "$audioCard" ]; then
        cat > /etc/asound.conf <<EOF
# Autogenerated by dirtsim-config-setup.sh.
defaults.pcm.card ${audioCard}
defaults.ctl.card ${audioCard}
EOF
        echo "Set ALSA default card to ${audioCard}"
    fi
fi

# Ensure dirtsim user owns their home directory.
if [ -d /home/dirtsim ]; then
    chown -R dirtsim:dirtsim /home/dirtsim
    echo "Set ownership on /home/dirtsim"
fi

# Ensure dirtsim user owns their working directory.
if [ -d /data/dirtsim ]; then
    chown -R dirtsim:dirtsim /data/dirtsim
    echo "Set ownership on /data/dirtsim"
fi

exit 0
